### ISSUE TITLE
Add ability to add HWM files

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#272]
- [x] Add 'add file' button under the "HWM File Information" section

**Comment by Abigail770** [comment]
Should we also add the ability to Edit and Delete HWM files from the Edit HWM dialog?

**Comment by lprivette** [comment]
If we add the ability to Edit and Delete to the HWMs edit modal then we'll have to do the same for sensor file, ref datums files, site files in order to stay consistent. Though someone may find it frustrating, I'm wondering if it's acceptable to only allow edit/delete in the Files tab. And that in itself is a small qa check in a way. Thoughts? We can also get some feedback on only allowing edits/delete on files tab and make changes later based on that.

**Comment by chaqazarad** [comment]
I think that additional functionality could be deferred until later if you are concerned about time/effort (the basic functionality is there with the files tab). It's probably something we would want to eventually add. Whatever we decide we should make sure that the associated HWM shows in that file table. Also shouldn't the view modal at least show which HWM the file is associated with. (I'm assuming I have the file to HWM relationship right)

**Comment by Abigail770** [comment]
That would make sense to me since it seems like adding would be the primary action and Edit/Delete would be used less frequently.  I wonder if users do editing and deleting by click on the file in old STN, or if they usually open up a sensor/hwm, etc. and then go to file information.

We do have the edit/delete for Site files in the Site Edit dialog - we could eliminate that to be consistent though.  I have the HWM File Add dialog opening from the HWM Edit modal right now vs. the form being added to the edit modal (which is how the site edit file section is set up).  Not sure which is preferred

**Comment by chaqazarad** [comment]
Oh I didn't know you had to click the file to open the dialog (thats kinda unintuitive). I think we should leave it for now, come back and do them all as: A table with inline edit and delete icon/buttons. Edit would just transition to a new modal. Instead of doing the sub-expand/collapse thing it has going on. But I leave it up to lauren.

**Comment by lprivette** [comment]
Agree with the inline additions to that dialog. Not excited about another modal transition, but agree we can come back to this. 

Ok so lets defer on the additional functionality in the edit modals (to focus on MVP push). And leave the site edit as is. I'll make an issue for addressing the file click/inline edit.
