### ISSUE TITLE
Remove 2nd nav; and event indicators 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#296]
See Daniel's mockups below.
- [x] remove blue/gray navbar
- [ ] breadcrumb text are links and used to navigate backwards
- [ ] site breadcrumb should be the site id for example: NCONS13128

**Comment by lprivette** [comment]
![image](https://user-images.githubusercontent.com/23640741/145650167-c812e1cc-d76b-4a36-beda-9ef954d5a981.png)

![image](https://user-images.githubusercontent.com/23640741/145649955-99c397c7-3ee9-48d5-b08a-39ca4b431af8.png)

**Comment by Abigail770** [comment]
A couple styling questions:
1.  Will we want the session event on the map page to be "stuck" at the top of the map rather than staying visible as the user scrolls down?  Snackbar behavior shows the snackbar at all times when scrolling, but we could potentially override the default behavior or make it a mat-card component.
![image](https://user-images.githubusercontent.com/54085652/152384294-048b3c72-956a-4ada-b001-e56d111d323e.png)
2.  How necessary is the minimize/maximize map capability?  Is it something we could consider eliminating?  If not, maybe we could position it somewhere else (possibly at the bottom of the map).

**Comment by lprivette** [comment]
1. I would commandeer the Minimize Map button and put it there, and not have it scroll with the page like it's already doing
2. I'll make an issue for this. The point of the that was to collapse the space and make the table easier to view but it's not really doing that with the map filters the way they are. I'm thinking a 'jump to results' would be more helpful

**Comment by chaqazarad** [comment]
I agree the minimize map button isnt the most useful but would be a good place to put the session event.
