### ISSUE TITLE
Add 'Jump to Results' button to map 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#363]
The two places I'm thinking it could go: 
![image](https://user-images.githubusercontent.com/23640741/152390668-6dc9905e-abd8-4a24-8830-99f70f8239d0.png)

So it'd be a small icon on the left or a bigger text button if at the top. 

Up for discussion or others opinions on this.

**Comment by chaqazarad** [comment]
Couple ideas you could consider
![image](https://user-images.githubusercontent.com/85179214/152409092-690848e2-3216-4f1e-99dd-706428fb82c8.png)
![image](https://user-images.githubusercontent.com/85179214/152409114-466e253f-5e7a-4898-963b-c34ec6271ec2.png)
![image](https://user-images.githubusercontent.com/85179214/152409147-8eb2b50c-c796-45ff-9a2a-e0e76e9ef099.png)
![image](https://user-images.githubusercontent.com/85179214/152409201-275af4c1-feea-4f41-8e4f-2cbcd7dbbc1a.png)

**Comment by Abigail770** [comment]
I like option 1 a lot where it's at the bottom of the map.  That might make things too crowded on mobile though.  If we went with option 1, on mobile maybe we could move it below the Map Filters button:
![image](https://user-images.githubusercontent.com/54085652/152429007-a5856154-a3ec-4ff8-929e-3968774df748.png)

**Comment by chaqazarad** [comment]
I like the first option the best as well. Maybe we just hide it on mobile? I don't know. I'm not sure if its worth considering too much because at some point in the future we will need to go back and do some mobile optimization. There are a bunch of other things that need to be fixed for mobile already. What do you think?

**Comment by Abigail770** [comment]
That's true.  It sounds like STN is used mostly on desktop too so desktop placement is probably the most important.

**Comment by Abigail770** [comment]
For the breadcrumbs, do we want it set up so they're in order of the pages the user viewed (viewed map > viewed site details > viewed user > viewed site again > viewed another site, etc), or webpage hierarchy (map > a site, map > users, map > a different site)?  Webpage hierarchy to me would make sense since there is a clear hierarchy with map vs site pages, but I'm not sure what the most common use is.

**Comment by chaqazarad** [comment]
definitely webpage hierarchy
