### ISSUE TITLE
Add ability to retrieve deployed sensor

### ISSUE THREAD

**Issue by Abigail770** [USGS-WiM/stnweb2#389]
Circled in red are a few potential places we could add a retrieve button.  We could have a button either in the status or button column in the table, and then add it to the hidden menu on mobile like we do with the other buttons.
![retrieveSensor](https://user-images.githubusercontent.com/54085652/169158025-1c7422e3-26f3-449e-b311-9e037d8e8c0e.PNG)

**Comment by lprivette** [comment]
I'm feeling in the button column with the hidden menu on mobile. Thoughts on giving it a different outline color since it's atypical action that is important during deployments? we could also left-align the button to make it a little more separated from the main group of buttons and it'd be closer to the status column that its related to. 

I am late getting to this though so if you already implemented something just stick with that and we can see how that looks/works

**Comment by Abigail770** [comment]
This is what I've got so far for desktop and mobile.  We can easily change the color and shouldn't be too hard to change the alignment if we do want to go with left-aligned.  I also picked an icon for mobile that seemed to sort of fit, since the other buttons have icons on mobile.  But we may want to go with a different icon (or no icon at all).
![retrieveSensor1](https://user-images.githubusercontent.com/54085652/169611548-031e0202-cff9-4a0b-815c-54b642ff9e67.PNG)
![image](https://user-images.githubusercontent.com/54085652/169611553-3e51b3da-b064-48d7-af24-67fa69f7bec2.png)

**Comment by lprivette** [comment]
What about moving it to the left of the view details for desktop?  thinking it might be good to keep the buttons that are always present the same in each row.

Retrieve icon looks good!

also would totally welcome @chaqazarad opinion on this. I don't feel confident in these kinds of design decisions ha.
