### ISSUE TITLE
Event Filter Selection

### ISSUE THREAD

**Issue by chaqazarad** [USGS-WiM/stnweb2#406]
Some wonky issues with the event filters. 

- [ ] Can't select a different state after selecting a state. Must use clear filters button.
- [ ] After selecting an event the drop down only populates with your previously selected event.

**Comment by Abigail770** [comment]
Since the event/state dropdowns are filtered according to what the user is typing, the dropdowns are only populated with all options when no options are selected/typed in.  To get the full list of options, the user has to actually backspace/delete the existing text.  For example:

1. Filter by State: Wisconsin, Event Name: Wisconsin July 2016 (or any state/event name)
2. Click Filter Sites
3. Click in the State filter as if to type, and delete/backspace text
4. Dropdown should be populated with all state options

We can change this functionality (maybe only have a dropdown, no typing/filtering) if that's what most users would expect.

**Comment by chaqazarad** [comment]
I think it makes more sense once you understand that you need to delete/backspace text. I think if we just added a clear "x" the state and event filters it would solve the problem. See: https://designsystem.digital.gov/components/combo-box/

**Comment by Abigail770** [comment]
Good idea, I like this solution! I'll add a clear "x" button
