### ISSUE TITLE
Set up Legend

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#67]
We'll need to show the layer info for esri map services.

**Comment by 09Kathy** [comment]
Should we make this look like WHIPers with the control moved to the left and the legend in this style?
![image](https://user-images.githubusercontent.com/46943254/99574874-87360200-299d-11eb-9a55-3d5d73fe473e.png)

**Comment by lprivette** [comment]
I'm thinking we move the layer control to the right of the zoom buttons.
![image](https://user-images.githubusercontent.com/23640741/99576887-90789c00-29a8-11eb-81ef-72069e18e1c7.png)


And then put the legend on the right side of the map like where it is in whispers

**Comment by 09Kathy** [comment]
Seems like in order to customize the location of the control beyond the four options provided by leaflet, you need to write out all the code, which means that the interaction with the legend will also need to be hardcoded (I tried making my own .leaflet-control-layers class to override it, but no luck so far). This is a similar problem to what we had in doi fev, we might need to do it anyway if we want to do anything else that's fancier than what leaflet can give us in the future. Should I go forward with that or leave it be? I'm thinking the home button next to the zoom buttons could be a good spot because both are about map extent and can hardcode later if needed. Here are some of the options:
![image](https://user-images.githubusercontent.com/46943254/99583224-ca49a280-29a8-11eb-97be-83eadba7fe0d.png)
and with control open:
![image](https://user-images.githubusercontent.com/46943254/99583332-f2d19c80-29a8-11eb-95bb-0b6cf94a811d.png)
hardcoded control:
![image](https://user-images.githubusercontent.com/46943254/99583565-51971600-29a9-11eb-89c4-71f1699215b1.png)
